{"name": "test_div", "status": "failed", "statusDetails": {"message": "AssertionError: failed\nassert 1 == 7", "trace": "self = <Case.test_work.TestNum object at 0x10c27fbe0>\n\n    def test_div(self):\n        a = 3\n        b = 4\n        sum = b - a\n>       assert sum == 7, \"failed\"\nE       AssertionError: failed\nE       assert 1 == 7\n\ncase/test_work.py:15: AssertionError"}, "start": 1574061436316, "stop": 1574061436316, "uuid": "6d251541-30a8-41c2-982b-17fd813d8efb", "historyId": "0fd3a14ddd883c8d929853dffccc43a3", "testCaseId": "fd7f7623fe9b7f79844c495d4118612e", "fullName": "Case.test_work.TestNum#test_div", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestNum"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "4015-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_work"}]}