{"name": "test_div", "status": "failed", "statusDetails": {"message": "AssertionError: failed\nassert 1 == 7", "trace": "self = <Case.test_num.TestNum object at 0x10c158b70>\n\n    def test_div(self):\n        a = 3\n        b = 4\n        sum = b - a\n>       assert sum == 7, \"failed\"\nE       AssertionError: failed\nE       assert 1 == 7\n\ncase/test_num.py:15: AssertionError"}, "start": 1574061225004, "stop": 1574061225005, "uuid": "db7ded15-d51e-4d11-87a2-e42c40e3a397", "historyId": "829332fd94dcd52cd819c4e4553d6006", "testCaseId": "4655c6781fd568fee1c3f604fac6966c", "fullName": "Case.test_num.TestNum#test_div", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_num"}, {"name": "subSuite", "value": "TestNum"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "4015-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_num"}]}