{"name": "test_div", "status": "failed", "statusDetails": {"message": "AssertionError: failed\nassert 1 == 7", "trace": "self = <case1.test_work.TestNum object at 0x101abd240>\n\n    def test_div(self):\n        a = 3\n        b = 4\n        sum = b - a\n>       assert sum == 7, \"failed\"\nE       AssertionError: failed\nE       assert 1 == 7\n\ncase1/test_work.py:15: AssertionError"}, "start": 1574063995702, "stop": 1574063995702, "uuid": "c35c53ec-88a8-450a-a45d-40c7250f2f4a", "historyId": "07e9050e27b6e2e98d3911be95d8e934", "testCaseId": "e2f068b104be335d5a66632f5d2487ae", "fullName": "case1.test_work.TestNum#test_div", "labels": [{"name": "parentSuite", "value": "case1"}, {"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestNum"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "4733-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case1.test_work"}]}