{"name": "test_div", "status": "failed", "statusDetails": {"message": "AssertionError: failed\nassert 1 == 7", "trace": "self = <case1.test_num.TestNum object at 0x101a9ed30>\n\n    def test_div(self):\n        a = 3\n        b = 4\n        sum = b - a\n>       assert sum == 7, \"failed\"\nE       AssertionError: failed\nE       assert 1 == 7\n\ncase1/test_num.py:15: AssertionError"}, "start": 1574063995677, "stop": 1574063995677, "uuid": "ee75da35-2228-412e-a9b6-bf3604da6719", "historyId": "a4fbcef545a7e57c68135b847a77ac87", "testCaseId": "3c767e915ded3654a7dec2adef77b3b5", "fullName": "case1.test_num.TestNum#test_div", "labels": [{"name": "parentSuite", "value": "case1"}, {"name": "suite", "value": "test_num"}, {"name": "subSuite", "value": "TestNum"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "4733-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case1.test_num"}]}