{"name": "test_sub", "status": "failed", "statusDetails": {"message": "AssertionError: failed\nassert 1 == 7", "trace": "self = <Case.test_work.TestNum object at 0x10bbc02e8>\n\n    def test_sub(self):\n        a = 3\n        b = 4\n        sum = b - a\n>       assert sum == 7, \"failed\"\nE       AssertionError: failed\nE       assert 1 == 7\n\nCase/test_work.py:27: AssertionError"}, "start": 1575962893936, "stop": 1575962893936, "uuid": "78481070-a0c8-41cf-8195-65c7e7449c6b", "historyId": "b7ae6474199f05a8e3157b7b0830b431", "testCaseId": "f4d244852af33ba01d777024b9deef35", "fullName": "Case.test_work.TestNum#test_sub", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestNum"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "17469-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_work"}]}