{"name": "test_sub", "status": "failed", "statusDetails": {"message": "AssertionError: failed\nassert 1 == 7", "trace": "self = <case1.test_work1.TestNum object at 0x10bb2c7f0>\n\n    def test_sub(self):\n        a = 3\n        b = 4\n        sum = b - a\n>       assert sum == 7, \"failed\"\nE       AssertionError: failed\nE       assert 1 == 7\n\ncase1/test_work1.py:27: AssertionError"}, "start": 1574068503163, "stop": 1574068503163, "uuid": "8b9bbc36-2599-49c0-8f52-b3b024087b04", "historyId": "a1b55049f56b905cff7e2ee28684772a", "testCaseId": "34bd8bfe4e1e55fba2d7e8772d5492c7", "fullName": "case1.test_work1.TestNum#test_sub", "labels": [{"name": "parentSuite", "value": "case1"}, {"name": "suite", "value": "test_work1"}, {"name": "subSuite", "value": "TestNum"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "5478-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case1.test_work1"}]}