{"name": "test_div", "status": "failed", "statusDetails": {"message": "AssertionError: failed\nassert 1 == 7", "trace": "self = <case1.test_work.TestNum object at 0x10baff240>\n\n    def test_div(self):\n        a = 3\n        b = 4\n        sum = b - a\n>       assert sum == 7, \"failed\"\nE       AssertionError: failed\nE       assert 1 == 7\n\ncase1/test_work.py:15: AssertionError"}, "start": 1574068503135, "stop": 1574068503135, "uuid": "c8fc3f61-4b99-4749-96bd-d30c58f1f640", "historyId": "07e9050e27b6e2e98d3911be95d8e934", "testCaseId": "e2f068b104be335d5a66632f5d2487ae", "fullName": "case1.test_work.TestNum#test_div", "labels": [{"name": "parentSuite", "value": "case1"}, {"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestNum"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "5478-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case1.test_work"}]}