{"name": "test_sub", "status": "failed", "statusDetails": {"message": "AssertionError: failed\nassert 1 == 7", "trace": "self = <case1.test_work.TestNum object at 0x10baff630>\n\n    def test_sub(self):\n        a = 3\n        b = 4\n        sum = b - a\n>       assert sum == 7, \"failed\"\nE       AssertionError: failed\nE       assert 1 == 7\n\ncase1/test_work.py:27: AssertionError"}, "start": 1574068503147, "stop": 1574068503147, "uuid": "ebcd978d-2edc-4a20-9c2b-5a79ad476405", "historyId": "cfbe29c96b74b5e58be2fb54b198f0f3", "testCaseId": "bea39ae430f92e1d7ecb87199d054967", "fullName": "case1.test_work.TestNum#test_sub", "labels": [{"name": "parentSuite", "value": "case1"}, {"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestNum"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "5478-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case1.test_work"}]}