{"name": "test_div", "status": "failed", "statusDetails": {"message": "AssertionError: failed\nassert 1 == 7", "trace": "self = <case1.test_work1.TestNum object at 0x10baffda0>\n\n    def test_div(self):\n        a = 3\n        b = 4\n        sum = b - a\n>       assert sum == 7, \"failed\"\nE       AssertionError: failed\nE       assert 1 == 7\n\ncase1/test_work1.py:15: AssertionError"}, "start": 1574068503154, "stop": 1574068503154, "uuid": "cc3b745d-9aa6-4984-ab06-436aa7e196ce", "historyId": "d27df30e5eef54b1a47f8e5878bedfec", "testCaseId": "a96b8e0167086cd539e19005ee5602a9", "fullName": "case1.test_work1.TestNum#test_div", "labels": [{"name": "parentSuite", "value": "case1"}, {"name": "suite", "value": "test_work1"}, {"name": "subSuite", "value": "TestNum"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "5478-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case1.test_work1"}]}