{"name": "test_div", "status": "failed", "statusDetails": {"message": "AssertionError: failed\nassert 1 == 7", "trace": "self = <case.test_num.TestNum object at 0x104743dd8>\n\n    def test_div(self):\n        a = 3\n        b = 4\n        sum = b - a\n>       assert sum == 7, \"failed\"\nE       AssertionError: failed\nE       assert 1 == 7\n\ncase/test_num.py:15: AssertionError"}, "start": 1574046475778, "stop": 1574046475778, "uuid": "f873dfeb-d92f-4f2d-9056-d11c1cdd5061", "historyId": "f73d16c7b0478ed98507807e766fa821", "testCaseId": "c94b9498176353611029e4dbef1c8e1d", "fullName": "case.test_num.TestNum#test_div", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_num"}, {"name": "subSuite", "value": "TestNum"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "957-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_num"}]}